volumes:
  postgres_data:
    name: postgres_data
  frontend:
    name: frontend
  redis:
    name: redis
  certs:
    name: certs
  elasticsearch:
    name: elasticsearch
  kibana:
    name: kibana
  prometheus:
    name: prometheus
  alertmanager:
    name: alertmanager
  grafana:
    name: grafana

networks:
  ft_transcendence:
    name: ft_transcendence
  elk-stack:
    name: elk-stack
  prom-graf:
    name: prom-graf

services:

  # Web App
  frontend:
    extends:
      file: ./app/compose.app.yml
      service: frontend
  backend:
    extends:
      file: ./app/compose.app.yml
      service: backend
  postgres:
    extends:
      file: ./database/compose.database.yml
      service: postgres
  redis:
    extends:
      file: ./database/compose.database.yml
      service: redis
  nginx:
    extends:
      file: ./nginx/compose.nginx.yml
      service: nginx
  
  # ELK-Stack
  setup:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: setup
  elasticsearch:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: elasticsearch
  kibana:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: kibana
  logstash:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: logstash
  
  # Prometheus & Grafana
  prometheus:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: prometheus
  grafana:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: grafana
  
  # Exporters
  nginx-exporter:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: nginx-exporter
  redis-exporter:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: redis-exporter
  postgres-exporter:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: postgres-exporter
  node-exporter:
    extends:
      file: ./SRE-SLI/compose.sre.yml
      service: node-exporter