groups:
  - name: all-instances-alerts
    rules:
      - alert: Instance-Status-Change
        expr: up == 0
        for: 20s
        annotations:
          summary: "Status Change Detected"
          description: "[{{ $labels.instance }}] Instance in [{{ $labels.job }}] Job is experiencing status changes."