version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    build:
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    networks:
      - ft_transcendence
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

  redis:
    image: redis
    container_name: redis
    build:
      dockerfile: Dockerfile.redis
    volumes:
      - redis:/data
    networks:
      - ft_transcendence
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 5s